language: node_js
node_js: 6
install:
- npm i
- npm i -g gulp
- echo -ne '\n\e[B\npublic/semantic/\n' | npm i semantic-ui --save
- cd public/semantic && gulp build
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: qmm1kjZqdgoLviJxpo1BNgAvIIkn+C7Toy+R7K1VDQnXSsJCnlcabfmPKw2LP/pkQ6V05SXLtCe6g2OEoe+ZYAva+gw3DTKOdFR8TG05CYxX0NYNEeRteIeGsAkahtF5KbfWuMd+iAjl1bEFSq4w0Aw+emTx8mOvtEvaP+i7nUeXca6pYzNAQWKBA47iUD0HK1uIWhCtD0LilROEmhh0sjYdYfbl2LK7dFL50nUSxoaxg7TWg8Mm8gEpujNoISJ5KSPjs7qEyZ+wGzX2iq7bcOSwSPcWm4HgbU2oGJdwVkWZae8D4cVDyTxO6zhubSZUMkXvYWJ/LTOH7naRdgp/aI0ILntoiq9inLd0DKvOC2hYNzOapB64slXYt2SH/xjXtH6ntAn1ylKHBPLRbVbSKrS40ktxyTb1zEGPf/8uzfXFzVKkyHRbZR0Utx7zzKdYI9y3YfJ3dMQqR8rIsPT+sEoVEWGozFTxuCzs6SsKXsCoHP1WwAQrFoySdL2cxAo22ZC2xD7xjhPrZsOIyd/nz5bKwNcvSzENOmpTjn6qZJQ1hQ8xKDoi6b1J9et8tSbL7ApBsIgcnZS2gZubyHLEl3F94Qp9ZNz0EyWS0/Gqz/2NS7gZ44AIwaInPBslKcqobhlgMqGLd2LtAq09Y8eKGvy4HGYZTlawKerKJFKucKY=
  app: sematest
  on:
    repo: avtyul/sematest
